# Configuration Settings for the Rover Rx

# GNSS/INS Parameters

device: tcp://192.168.3.1:28784

serial:
  baudrate: 921600
  hw_flow_control: "off"

stream_device:
  tcp:
    ip_server: ""
    port: 0
  udp:
    ip_server: ""
    port: 0
    unicast_ip: ""

configure_rx: true

login:
  user: ""
  password: ""

osnma:
  mode: "loose"
  ntp_server: ""
  keep_open: true

frame_id: gnss

aux1_frame_id: aux1

get_spatial_config_from_tf: true

use_ros_axis_orientation: true

receiver_type: gnss

multi_antenna: false

datum: Default

att_offset:
  heading: 0.0
  pitch: 0.0

ant_type: "Unknown"
ant_serial_nr: "Unknown"
ant_aux1_type: "Unknown"
ant_aux1_serial_nr: "Unknown"

polling_period:
  pvt: 0
  nav_page: 0
  rest: 500

use_gnss_time: false

latency_compensation: false

rtk_settings:  
  ntrip_1:
    id: ""
    caster: ""
    caster_port: 2101
    username: ""
    password: ""
    mountpoint: ""
    version: "v2"
    tls: false
    fingerprint: ""
    rtk_standard: "auto"
    send_gga: "auto"
    keep_open: true
  ip_server_1:
    id: ""
    port: 0
    rtk_standard: "auto"
    send_gga: "auto"
    keep_open: true
  serial_1:
    port: ""
    baud_rate: 115200
    rtk_standard: "auto"
    send_gga: "auto"
    keep_open: true

publish:
  # For both GNSS and INS Rxs
  navsatfix: false
  gpsfix: true
  gpgga: true
  gprmc: true
  gpst: true
  measepoch: true
  gpsnav: true
  galnav: true
  measextra: true
  pvtcartesian: true
  pvtgeodetic: true
  basevectorcart: false
  basevectorgeod: false
  poscovcartesian: false
  poscovgeodetic: false
  velcovcartesian: false
  velcovgeodetic: false
  pose: false
  twist: false
  diagnostics: false
  aimplusstatus: false
  galauthstatus: false
  gpsrawca: false
  glorawca: false
  galrawfnav: false
  galrawinav: false
  galrawcnav: false
  bdsraw: false
  # For GNSS Rx only
  gpgsa: false
  gpgsv: false

signals_to_track:
  - "GPSL1CA"
  - "GPSL2PY"
  - "GPSL2C"
  - "GPSL5"
  - "GLOL1CA"
  - "GLOL2CA"
  - "GLOL2P"
  - "GALL1BC"
  - "GALE5a"
  - "GALE5b"
  - "GALE5"
  - "BDSB1I"
  - "GALE6BC"
# logger

activate_debug_log: false